### ISSUE TITLE
Export all SMDAST types from one module

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/markdown#32]
**User story.**
As a developer I can `import * as something from '@stoplight/markdown/some-file'` to get all the SMDAST types and nothing more. 

**Is your feature request related to a problem?**
See discussion at https://github.com/stoplightio/markdown-viewer/pull/49#discussion_r427305083 

**Describe the solution you'd like**
Have a file that exports only the types, and then the main smdast.ts would just `export * from 'file-with-types'`. This way backwards compatibility is kept, this is not a breaking change, just an added feature.

**Comment by P0lip** [comment]
I might be missing something, but isn't https://github.com/stoplightio/markdown/blob/master/src/ast-types/smdast/index.ts excactly what we are looking for here?
SMDAst stands for Stoplight mdast, so in other words it's a superset of mdast, therefore it re-exports unchanged parts of mdast as well as Stoplight mdast additions.

**Comment by marcelltoth** [comment]
I think I used the wrong word. By *SMDAST types* I mean the actual element types, stuff that extends `{ type: string; }` basically. Stuff I can build a discriminated union from (based on the `type` property).

The problem with `smdast/index.ts` is that it also exports "crap" like `AnnotationType` or `IAnnotations`, etc.

**Comment by P0lip** [comment]
Ah, yeah, I get it now.
Yes, that makes sense, in particular when it comes to our use of types in markdown-viewer.
Go for it!

**Comment by marcelltoth** [comment]
Unfortunately this does not work in TypeScript. 

Looks like TS cannot infer the module types as a whole for some reason:
![image](https://user-images.githubusercontent.com/543372/82891747-f4209000-9f56-11ea-8645-edd76490bee8.png)
![image](https://user-images.githubusercontent.com/543372/82891795-07336000-9f57-11ea-8edb-4cecc7127f75.png)

@P0lip any guesses maybe? I tried everything I could find, but it looks like we'll just have to keep unioning stuff by hand.

**Comment by P0lip** [comment]
@marcelltoth 
```ts
import type * as A from './ast-types/smdast/element-types'

const x: A.IElement = {};
```
seems to work correctly.
The only caveat is that we use older version of prettier and it complains about the syntax.
Oh, and `A` is a namespace, unfortunately :/ 

EDIT:
Ah, nvm, it seems like you've already tried with the namespace. Didn't see the second screenshot.

**Comment by P0lip** [comment]
Maybe @XVincentX knows how to avoid unioning of each namespace member?

**Comment by marcelltoth** [comment]
Somehow Blueprint manages it: https://github.com/palantir/blueprint/blob/develop/packages/icons/src/iconName.ts

I don't know why it isn't working in our case. @P0lip Can you confirm that something like this doesn't work for you either?
```typescript
// some-file.ts
export type A {
  type: 'A';
}
export type B {
  type: 'B';
}

// some-other-file.ts
import * as T from './some-file.ts`
type UnionOfT = typeof T[keyof typeof T]; // just like blueprint
declare const someConst: UnionOfT;
console.log(someConst.type); // THIS GIVES ME AN ERROR, as the union is considered `never` for some reason
```

**Comment by marcelltoth** [comment]
The discussion with @XVincentX ended with "this is most likely not possible in current TypeScript" so I'm just going to close this. 😢 

(The blueprint one works because their export is an actual object. Ours is just types, so it gets eliminated.)
